#!/usr/bin/env python3
"""Generate C q-format constants from FxP/core/qformats.yaml.

The manifest is JSON-compatible YAML for zero external dependencies.
"""

from __future__ import annotations

import json
import pathlib
import sys


def _as_int(entry: dict, key: str) -> int:
    value = entry.get(key)
    if not isinstance(value, int):
        raise ValueError(f"{entry.get('id', '<unknown>')}: '{key}' must be an integer")
    return value


def _as_bool(entry: dict, key: str) -> bool:
    value = entry.get(key)
    if not isinstance(value, bool):
        raise ValueError(f"{entry.get('id', '<unknown>')}: '{key}' must be a boolean")
    return value


def _as_id(entry: dict, key: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str) or not value:
        raise ValueError(f"Entry missing valid '{key}'")
    if not all(ch.isupper() or ch.isdigit() or ch == "_" for ch in value):
        raise ValueError(f"{value}: id must use [A-Z0-9_]")
    return value


def generate(manifest_path: pathlib.Path, out_path: pathlib.Path) -> None:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    qformats = data.get("qformats")
    if not isinstance(qformats, list) or not qformats:
        raise ValueError("Manifest must contain a non-empty 'qformats' list")

    seen_ids = set()
    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Generated by FxP/tools/generate_qformats.py from FxP/core/qformats.yaml.")
    lines.append("// Do not hand-edit this file; regenerate it from the manifest.")
    lines.append("")

    for entry in qformats:
        if not isinstance(entry, dict):
            raise ValueError("Each qformats item must be an object")

        qid = _as_id(entry, "id")
        if qid in seen_ids:
            raise ValueError(f"Duplicate id '{qid}'")
        seen_ids.add(qid)

        bits = _as_int(entry, "total_bits")
        frac = _as_int(entry, "frac_bits")
        signed = _as_bool(entry, "signed")

        if bits not in (16, 32, 64):
            raise ValueError(f"{qid}: total_bits must be 16, 32, or 64")
        if frac < 0 or frac >= 63:
            raise ValueError(f"{qid}: frac_bits must be in [0, 62]")

        sign_macro = 1 if signed else 0
        lines.append(f"#define FXP_BITS_{qid} {bits}")
        lines.append(f"#define FXP_FRAC_{qid} {frac}")
        lines.append(f"#define FXP_SIGNED_{qid} {sign_macro}")
        lines.append(f"#define FXP_SCALE_{qid}_U64 (1ULL << FXP_FRAC_{qid})")
        lines.append(f"#define FXP_SCALE_{qid}_F32 ((float)FXP_SCALE_{qid}_U64)")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    repo_root = pathlib.Path(__file__).resolve().parents[2]
    default_manifest = repo_root / "FxP" / "core" / "qformats.yaml"
    default_out = repo_root / "FxP" / "core" / "fxp_qformats.h"

    manifest = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else default_manifest
    out = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else default_out

    generate(manifest, out)
