# Configuration file for extracting features with the mel spectrogram audio features instead of the MFCCs

# Whether to extract training or testing features
ext_train_feats: True
ext_test_feats: True

# Epsilon-tolerance for the Douglas-Peucker algorithm used to compute the Approximate-Zero-Crossing (AZC) feature
DP_epsilon: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
#  Whether to extract MFCCs or mel spectrogram values and how many to extract
n_mfcc: 64
#  Decide whether to compute MFCCs (True) or simpler mel spectrogram components
compute_mfcc: False
#  Power spectral density frequency bands
psd_bands: [[0,50],[50,140],[160,350]] 
#  EEPD bandpass filter starting frequencies and bandwidth
eepd_bands: [50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950]