#!/usr/bin/env python3
"""
Generate fixed-point twiddle headers for Cough-E KissFFT.

Outputs:
  - twiddles_win08_fs8000_q15.h  (int16_t Q1.15)
  - twiddles_win08_fs8000_q31.h  (int32_t Q1.31)

The generated tables mirror the existing float twiddle sets:
  inner twiddles: 3200, 1024, 450
  super twiddles: 1600, 512, 225
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Iterable, List, Tuple


INNER_TABLES: List[Tuple[str, int]] = [
    ("twiddles_3200", 3200),
    ("twiddles_450", 450),
    ("twiddles_1024", 1024),
]

SUPER_TABLES: List[Tuple[str, int]] = [
    ("twiddles_1600", 1600),
    ("twiddles_225", 225),
    ("twiddles_512", 512),
]


def _quantize_unit(x: float, frac_bits: int) -> int:
    """
    Quantize unit-range value with signed Q1.frac_bits encoding.
    Uses scale = 2^frac_bits - 1 to avoid +1.0 overflow.
    """
    scale = (1 << frac_bits) - 1
    q = int(round(x * scale))
    if q > scale:
        q = scale
    if q < -scale:
        q = -scale
    return q


def _gen_inner_values(length: int, frac_bits: int) -> Iterable[Tuple[int, int]]:
    for i in range(length):
        phase = -2.0 * math.pi * float(i) / float(length)
        c = _quantize_unit(math.cos(phase), frac_bits)
        s = _quantize_unit(math.sin(phase), frac_bits)
        yield c, s


def _gen_super_values(length: int, frac_bits: int) -> Iterable[Tuple[int, int]]:
    # In kiss_fftr_alloc(), this corresponds to:
    # phase = -pi * ((i+1)/nfft + 0.5), where nfft is half the real-FFT size.
    nfft = length * 2
    for i in range(length):
        phase = -math.pi * (((float(i) + 1.0) / float(nfft)) + 0.5)
        c = _quantize_unit(math.cos(phase), frac_bits)
        s = _quantize_unit(math.sin(phase), frac_bits)
        yield c, s


def _write_table(lines: List[str], name: str, length: int, values: Iterable[Tuple[int, int]]) -> None:
    lines.append(f"static const twiddles_t {name}[{length}] = {{")
    for c, s in values:
        lines.append(f"    {{ {c}, {s} }},")
    lines.append("};")
    lines.append("")


def _render_header(format_name: str, ctype: str, frac_bits: int) -> str:
    guard = f"_TWIDDLES_WIN08_FS8000_{format_name.upper()}_H_"
    lines: List[str] = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("/*")
    lines.append(" * Auto-generated by gen_twiddles_fixed.py.")
    lines.append(f" * Format: {format_name.upper()} (signed Q1.{frac_bits}, carrier {ctype})")
    lines.append(" */")
    lines.append("typedef struct twiddles_entry")
    lines.append("{")
    lines.append(f"    {ctype} cosine;")
    lines.append(f"    {ctype} sine;")
    lines.append("} twiddles_t;")
    lines.append("")

    for table_name, length in INNER_TABLES:
        _write_table(lines, table_name, length, _gen_inner_values(length, frac_bits))

    for table_name, length in SUPER_TABLES:
        _write_table(lines, table_name, length, _gen_super_values(length, frac_bits))

    lines.append(f"#endif /* {guard} */")
    lines.append("")
    return "\n".join(lines)


def _emit(format_name: str, out_dir: Path) -> Path:
    if format_name == "q15":
        ctype = "int16_t"
        frac_bits = 15
    elif format_name == "q31":
        ctype = "int32_t"
        frac_bits = 31
    else:
        raise ValueError(f"Unsupported format: {format_name}")

    out_path = out_dir / f"twiddles_win08_fs8000_{format_name}.h"
    out_path.write_text(_render_header(format_name, ctype, frac_bits), encoding="utf-8")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate fixed-point KissFFT twiddle headers")
    parser.add_argument(
        "--formats",
        nargs="+",
        choices=["q15", "q31"],
        default=["q15", "q31"],
        help="Header formats to generate (default: q15 q31)",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Output directory for generated headers (default: kiss_fftr directory)",
    )
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for fmt in args.formats:
        path = _emit(fmt, args.out_dir)
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

