#pragma once

// Fixed-point Q-format constants used by the FxP implementation.

#define FXP_BITS_IMU_RAW 16
#define FXP_FRAC_IMU_RAW 5
#define FXP_SIGNED_IMU_RAW 1
#define FXP_SCALE_IMU_RAW_U64 (1ULL << FXP_FRAC_IMU_RAW)
#define FXP_SCALE_IMU_RAW_F32 ((float)FXP_SCALE_IMU_RAW_U64)

#define FXP_BITS_IMU_L2A 16
#define FXP_FRAC_IMU_L2A 6
#define FXP_SIGNED_IMU_L2A 0
#define FXP_SCALE_IMU_L2A_U64 (1ULL << FXP_FRAC_IMU_L2A)
#define FXP_SCALE_IMU_L2A_F32 ((float)FXP_SCALE_IMU_L2A_U64)

#define FXP_BITS_IMU_L2G 16
#define FXP_FRAC_IMU_L2G 11
#define FXP_SIGNED_IMU_L2G 0
#define FXP_SCALE_IMU_L2G_U64 (1ULL << FXP_FRAC_IMU_L2G)
#define FXP_SCALE_IMU_L2G_F32 ((float)FXP_SCALE_IMU_L2G_U64)

#define FXP_BITS_AUDIO_INPUT 16
#define FXP_FRAC_AUDIO_INPUT 14
#define FXP_SIGNED_AUDIO_INPUT 1
#define FXP_SCALE_AUDIO_INPUT_U64 (1ULL << FXP_FRAC_AUDIO_INPUT)
#define FXP_SCALE_AUDIO_INPUT_F32 ((float)FXP_SCALE_AUDIO_INPUT_U64)

#define FXP_BITS_IMU_RMS_RAW 16
#define FXP_FRAC_IMU_RMS_RAW 3
#define FXP_SIGNED_IMU_RMS_RAW 0
#define FXP_SCALE_IMU_RMS_RAW_U64 (1ULL << FXP_FRAC_IMU_RMS_RAW)
#define FXP_SCALE_IMU_RMS_RAW_F32 ((float)FXP_SCALE_IMU_RMS_RAW_U64)

#define FXP_BITS_IMU_RMS_L2A 16
#define FXP_FRAC_IMU_RMS_L2A 3
#define FXP_SIGNED_IMU_RMS_L2A 0
#define FXP_SCALE_IMU_RMS_L2A_U64 (1ULL << FXP_FRAC_IMU_RMS_L2A)
#define FXP_SCALE_IMU_RMS_L2A_F32 ((float)FXP_SCALE_IMU_RMS_L2A_U64)

#define FXP_BITS_IMU_RMS_L2G 16
#define FXP_FRAC_IMU_RMS_L2G 9
#define FXP_SIGNED_IMU_RMS_L2G 0
#define FXP_SCALE_IMU_RMS_L2G_U64 (1ULL << FXP_FRAC_IMU_RMS_L2G)
#define FXP_SCALE_IMU_RMS_L2G_F32 ((float)FXP_SCALE_IMU_RMS_L2G_U64)

#define FXP_BITS_IMU_LINE_LENGTH_RAW 16
#define FXP_FRAC_IMU_LINE_LENGTH_RAW 9
#define FXP_SIGNED_IMU_LINE_LENGTH_RAW 0
#define FXP_SCALE_IMU_LINE_LENGTH_RAW_U64 (1ULL << FXP_FRAC_IMU_LINE_LENGTH_RAW)
#define FXP_SCALE_IMU_LINE_LENGTH_RAW_F32 ((float)FXP_SCALE_IMU_LINE_LENGTH_RAW_U64)

#define FXP_BITS_IMU_LINE_LENGTH_L2G 16
#define FXP_FRAC_IMU_LINE_LENGTH_L2G 9
#define FXP_SIGNED_IMU_LINE_LENGTH_L2G 0
#define FXP_SCALE_IMU_LINE_LENGTH_L2G_U64 (1ULL << FXP_FRAC_IMU_LINE_LENGTH_L2G)
#define FXP_SCALE_IMU_LINE_LENGTH_L2G_F32 ((float)FXP_SCALE_IMU_LINE_LENGTH_L2G_U64)

#define FXP_BITS_IMU_KURTOSIS_RAW 32
#define FXP_FRAC_IMU_KURTOSIS_RAW 22
#define FXP_SIGNED_IMU_KURTOSIS_RAW 1
#define FXP_SCALE_IMU_KURTOSIS_RAW_U64 (1ULL << FXP_FRAC_IMU_KURTOSIS_RAW)
#define FXP_SCALE_IMU_KURTOSIS_RAW_F32 ((float)FXP_SCALE_IMU_KURTOSIS_RAW_U64)

#define FXP_BITS_IMU_CREST_L2G 16
#define FXP_FRAC_IMU_CREST_L2G 14
#define FXP_SIGNED_IMU_CREST_L2G 0
#define FXP_SCALE_IMU_CREST_L2G_U64 (1ULL << FXP_FRAC_IMU_CREST_L2G)
#define FXP_SCALE_IMU_CREST_L2G_F32 ((float)FXP_SCALE_IMU_CREST_L2G_U64)

#define FXP_BITS_IMU_KURT_VARIANCE 32
#define FXP_FRAC_IMU_KURT_VARIANCE 22
#define FXP_SIGNED_IMU_KURT_VARIANCE 0
#define FXP_SCALE_IMU_KURT_VARIANCE_U64 (1ULL << FXP_FRAC_IMU_KURT_VARIANCE)
#define FXP_SCALE_IMU_KURT_VARIANCE_F32 ((float)FXP_SCALE_IMU_KURT_VARIANCE_U64)

#define FXP_BITS_IMU_KURT_STD 16
#define FXP_FRAC_IMU_KURT_STD 11
#define FXP_SIGNED_IMU_KURT_STD 0
#define FXP_SCALE_IMU_KURT_STD_U64 (1ULL << FXP_FRAC_IMU_KURT_STD)
#define FXP_SCALE_IMU_KURT_STD_F32 ((float)FXP_SCALE_IMU_KURT_STD_U64)

#define FXP_BITS_IMU_KURT_STD4 64
#define FXP_FRAC_IMU_KURT_STD4 44
#define FXP_SIGNED_IMU_KURT_STD4 0
#define FXP_SCALE_IMU_KURT_STD4_U64 (1ULL << FXP_FRAC_IMU_KURT_STD4)
#define FXP_SCALE_IMU_KURT_STD4_F32 ((float)FXP_SCALE_IMU_KURT_STD4_U64)

#define FXP_BITS_AUDIO_FFT_RE_IM 32
#define FXP_FRAC_AUDIO_FFT_RE_IM 20
#define FXP_SIGNED_AUDIO_FFT_RE_IM 1
#define FXP_SCALE_AUDIO_FFT_RE_IM_U64 (1ULL << FXP_FRAC_AUDIO_FFT_RE_IM)
#define FXP_SCALE_AUDIO_FFT_RE_IM_F32 ((float)FXP_SCALE_AUDIO_FFT_RE_IM_U64)

#define FXP_BITS_AUDIO_FFT_MAGNITUDES 32
#define FXP_FRAC_AUDIO_FFT_MAGNITUDES 20
#define FXP_SIGNED_AUDIO_FFT_MAGNITUDES 0
#define FXP_SCALE_AUDIO_FFT_MAGNITUDES_U64 (1ULL << FXP_FRAC_AUDIO_FFT_MAGNITUDES)
#define FXP_SCALE_AUDIO_FFT_MAGNITUDES_F32 ((float)FXP_SCALE_AUDIO_FFT_MAGNITUDES_U64)

#define FXP_BITS_AUDIO_FFT_FREQUENCIES 32
#define FXP_FRAC_AUDIO_FFT_FREQUENCIES 20
#define FXP_SIGNED_AUDIO_FFT_FREQUENCIES 0
#define FXP_SCALE_AUDIO_FFT_FREQUENCIES_U64 (1ULL << FXP_FRAC_AUDIO_FFT_FREQUENCIES)
#define FXP_SCALE_AUDIO_FFT_FREQUENCIES_F32 ((float)FXP_SCALE_AUDIO_FFT_FREQUENCIES_U64)

#define FXP_BITS_AUDIO_FFT_SUM_MAGS 32
#define FXP_FRAC_AUDIO_FFT_SUM_MAGS 17
#define FXP_SIGNED_AUDIO_FFT_SUM_MAGS 0
#define FXP_SCALE_AUDIO_FFT_SUM_MAGS_U64 (1ULL << FXP_FRAC_AUDIO_FFT_SUM_MAGS)
#define FXP_SCALE_AUDIO_FFT_SUM_MAGS_F32 ((float)FXP_SCALE_AUDIO_FFT_SUM_MAGS_U64)

#define FXP_BITS_AUDIO_FFT_CENTROID 32
#define FXP_FRAC_AUDIO_FFT_CENTROID 21
#define FXP_SIGNED_AUDIO_FFT_CENTROID 0
#define FXP_SCALE_AUDIO_FFT_CENTROID_U64 (1ULL << FXP_FRAC_AUDIO_FFT_CENTROID)
#define FXP_SCALE_AUDIO_FFT_CENTROID_F32 ((float)FXP_SCALE_AUDIO_FFT_CENTROID_U64)

#define FXP_BITS_AUDIO_FFT_DEV 32
#define FXP_FRAC_AUDIO_FFT_DEV 19
#define FXP_SIGNED_AUDIO_FFT_DEV 1
#define FXP_SCALE_AUDIO_FFT_DEV_U64 (1ULL << FXP_FRAC_AUDIO_FFT_DEV)
#define FXP_SCALE_AUDIO_FFT_DEV_F32 ((float)FXP_SCALE_AUDIO_FFT_DEV_U64)

#define FXP_BITS_AUDIO_FFT_SPREAD 16
#define FXP_FRAC_AUDIO_FFT_SPREAD 5
#define FXP_SIGNED_AUDIO_FFT_SPREAD 0
#define FXP_SCALE_AUDIO_FFT_SPREAD_U64 (1ULL << FXP_FRAC_AUDIO_FFT_SPREAD)
#define FXP_SCALE_AUDIO_FFT_SPREAD_F32 ((float)FXP_SCALE_AUDIO_FFT_SPREAD_U64)

#define FXP_BITS_AUDIO_FFT_INV_SPREAD 32
#define FXP_FRAC_AUDIO_FFT_INV_SPREAD 20
#define FXP_SIGNED_AUDIO_FFT_INV_SPREAD 0
#define FXP_SCALE_AUDIO_FFT_INV_SPREAD_U64 (1ULL << FXP_FRAC_AUDIO_FFT_INV_SPREAD)
#define FXP_SCALE_AUDIO_FFT_INV_SPREAD_F32 ((float)FXP_SCALE_AUDIO_FFT_INV_SPREAD_U64)

#define FXP_BITS_AUDIO_FFT_NORM_DEV 16
#define FXP_FRAC_AUDIO_FFT_NORM_DEV 11
#define FXP_SIGNED_AUDIO_FFT_NORM_DEV 1
#define FXP_SCALE_AUDIO_FFT_NORM_DEV_U64 (1ULL << FXP_FRAC_AUDIO_FFT_NORM_DEV)
#define FXP_SCALE_AUDIO_FFT_NORM_DEV_F32 ((float)FXP_SCALE_AUDIO_FFT_NORM_DEV_U64)

#define FXP_BITS_AUDIO_FFT_NORM_DEV2 32
#define FXP_FRAC_AUDIO_FFT_NORM_DEV2 22
#define FXP_SIGNED_AUDIO_FFT_NORM_DEV2 0
#define FXP_SCALE_AUDIO_FFT_NORM_DEV2_U64 (1ULL << FXP_FRAC_AUDIO_FFT_NORM_DEV2)
#define FXP_SCALE_AUDIO_FFT_NORM_DEV2_F32 ((float)FXP_SCALE_AUDIO_FFT_NORM_DEV2_U64)

#define FXP_BITS_AUDIO_FFT_NORM_DEV4 32
#define FXP_FRAC_AUDIO_FFT_NORM_DEV4 12
#define FXP_SIGNED_AUDIO_FFT_NORM_DEV4 0
#define FXP_SCALE_AUDIO_FFT_NORM_DEV4_U64 (1ULL << FXP_FRAC_AUDIO_FFT_NORM_DEV4)
#define FXP_SCALE_AUDIO_FFT_NORM_DEV4_F32 ((float)FXP_SCALE_AUDIO_FFT_NORM_DEV4_U64)

#define FXP_BITS_AUDIO_FFT_KURT_WEIGHT 64
#define FXP_FRAC_AUDIO_FFT_KURT_WEIGHT 32
#define FXP_SIGNED_AUDIO_FFT_KURT_WEIGHT 0
#define FXP_SCALE_AUDIO_FFT_KURT_WEIGHT_U64 (1ULL << FXP_FRAC_AUDIO_FFT_KURT_WEIGHT)
#define FXP_SCALE_AUDIO_FFT_KURT_WEIGHT_F32 ((float)FXP_SCALE_AUDIO_FFT_KURT_WEIGHT_U64)

#define FXP_BITS_AUDIO_FFT_KURTOSIS 32
#define FXP_FRAC_AUDIO_FFT_KURTOSIS 15
#define FXP_SIGNED_AUDIO_FFT_KURTOSIS 0
#define FXP_SCALE_AUDIO_FFT_KURTOSIS_U64 (1ULL << FXP_FRAC_AUDIO_FFT_KURTOSIS)
#define FXP_SCALE_AUDIO_FFT_KURTOSIS_F32 ((float)FXP_SCALE_AUDIO_FFT_KURTOSIS_U64)

#define FXP_BITS_AUDIO_PSD_PROXY 32
#define FXP_FRAC_AUDIO_PSD_PROXY 11
#define FXP_SIGNED_AUDIO_PSD_PROXY 0
#define FXP_SCALE_AUDIO_PSD_PROXY_U64 (1ULL << FXP_FRAC_AUDIO_PSD_PROXY)
#define FXP_SCALE_AUDIO_PSD_PROXY_F32 ((float)FXP_SCALE_AUDIO_PSD_PROXY_U64)

#define FXP_BITS_AUDIO_PSD_INTEGRAL 32
#define FXP_FRAC_AUDIO_PSD_INTEGRAL 8
#define FXP_SIGNED_AUDIO_PSD_INTEGRAL 0
#define FXP_SCALE_AUDIO_PSD_INTEGRAL_U64 (1ULL << FXP_FRAC_AUDIO_PSD_INTEGRAL)
#define FXP_SCALE_AUDIO_PSD_INTEGRAL_F32 ((float)FXP_SCALE_AUDIO_PSD_INTEGRAL_U64)

#define FXP_BITS_AUDIO_PSD_FLATNESS 16
#define FXP_FRAC_AUDIO_PSD_FLATNESS 16
#define FXP_SIGNED_AUDIO_PSD_FLATNESS 0
#define FXP_SCALE_AUDIO_PSD_FLATNESS_U64 (1ULL << FXP_FRAC_AUDIO_PSD_FLATNESS)
#define FXP_SCALE_AUDIO_PSD_FLATNESS_F32 ((float)FXP_SCALE_AUDIO_PSD_FLATNESS_U64)

#define FXP_BITS_AUDIO_PSD_BANDPOWER 16
#define FXP_FRAC_AUDIO_PSD_BANDPOWER 16
#define FXP_SIGNED_AUDIO_PSD_BANDPOWER 0
#define FXP_SCALE_AUDIO_PSD_BANDPOWER_U64 (1ULL << FXP_FRAC_AUDIO_PSD_BANDPOWER)
#define FXP_SCALE_AUDIO_PSD_BANDPOWER_F32 ((float)FXP_SCALE_AUDIO_PSD_BANDPOWER_U64)
